# Generated by Django 4.1.7 on 2023-03-29 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_visible',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.TextField(max_length=470),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(max_length=470),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
