# Generated by Django 4.1.7 on 2023-03-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_category_desc_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.TextField(max_length=470, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='quality',
            field=models.IntegerField(null=True),
        ),
    ]
