# Generated by Django 4.1.7 on 2023-03-30 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_desc_category_quality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='quality',
        ),
    ]
