# Generated by Django 4.1.7 on 2023-03-30 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_category_quality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='desc',
            new_name='examples',
        ),
    ]
