# Generated by Django 4.1.7 on 2023-03-30 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quality',
            new_name='quantity',
        ),
    ]
