# Generated by Django 4.1.7 on 2023-04-20 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
