# Generated by Django 4.0.5 on 2023-05-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
